version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Running tests...
      - pytest  # or your test command
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
